# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for the version bump to read history

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: 'Automated Version Bump'
      id: version_bump
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: tatachristian12/demo-holvi-app
        tags: ${{ github.ref_name }}-${{ env.SHORT_SHA }},${{ env.APP_VERSION }},${{ github.ref_name }}-${{ env.SHORT_SHA }}-${{ env.APP_VERSION }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
