# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: 'Automated Version Bump'
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # 1. First, get the version from your file
    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
        # Also create a Short SHA for a cleaner tag
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    # 2. Then, build and push using the variables
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: tatachristian12/demo-holvi-app
        # Use a single line separated by commas, no spaces after commas
        tags: ${{ env.APP_VERSION }}-${{ github.ref_name }}-${{ env.SHORT_SHA }},${{ env.APP_VERSION }},${{ github.ref_name }}-${{ env.SHORT_SHA }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
